image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: Ti46nPnZgFh0nRteU6ma0EhJnCTW7PaMn9hnnewZl4gBFPyRQnXNCwGog02+MRLX

install:
- pip install -r requirements.txt

build_script:
- flet pack main.py --name sdc --icon assets\icon.png --product-name SMMEC --product-version "0.3.0" --copyright "Copyright (c) 2024 SMMEC Inc." --add-data "assets;assets"

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a sdc-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: sdc-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf sdc-macos.tar.gz -C dist sdc.app

  artifacts:
  - path: sdc-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf sdc-linux.tar.gz -C dist sdc

  artifacts:
  - path: sdc-linux.tar.gz

